In [4]:
#Reading the Dataset
import pandas as pd
import numpy as np
netflix = pd.read_csv('data_netflix.csv')
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [27]:
#info
netflix.info()

<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str
 2   title         6234 non-null   str
 3   director      4265 non-null   str
 4   cast          5664 non-null   str
 5   country       5758 non-null   str
 6   date_added    6223 non-null   str
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   str
 9   duration      6234 non-null   str
 10  listed_in     6234 non-null   str
 11  description   6234 non-null   str
 12  IMDB Rating   6234 non-null   float64
dtypes: float64(1), int64(2), str(10)
memory usage: 633.3 KB

In [29]:
netflix.shape

(6234, 13)

In [30]:
netflix.describe()

            show_id  release_year  IMDB Rating
count  6.234000e+03    6234.00000  6234.000000
mean   7.670368e+07    2013.35932     4.969185
std    1.094296e+07       8.81162     2.886845
min    2.477470e+05    1925.00000     0.000000
25%    8.003580e+07    2013.00000     2.400000
50%    8.016337e+07    2016.00000     4.900000
75%    8.024489e+07    2018.00000     7.500000
max    8.123573e+07    2020.00000    10.000000

In [10]:
#head - it will read first five lines of data
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,8.9
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2.2
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.0
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,3.3
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,9.2

In [11]:
#tail- it will read last five lines of data
netflix.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",0.0
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",8.9
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,2.0
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.2
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.6

In [5]:
#uniform() - for all rows 
IMDB=np.random.uniform(low=0,high=10,size=len(netflix['title']))
#to round up decimal - around()
IMDB=np.around(IMDB,decimals=1)
netflix['IMDB Rating']=IMDB
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,8.9
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2.2
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.0
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,3.3
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,9.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",0.0
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",8.9
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,2.0
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.2
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.6

Find how many items have 10 IMDB Rating (logical masking)

In [9]:
netflix[netflix['IMDB Rating']==10].count()

show_id         39
type            39
title           39
director        26
cast            32
country         34
date_added      39
release_year    39
rating          39
duration        39
listed_in       39
description     39
IMDB Rating     39
dtype: int64

In [15]:
netflix[netflix['IMDB Rating']==9.6]['title']

23                   Stonehearst Asylum
82                      Out of Thin Air
94                               Single
106                       Weeds on Fire
173                     Vincent N Roxxy
                     ...
5609           VeggieTales in the House
5631    Marvel's Agents of S.H.I.E.L.D.
5680          My Babysitter's a Vampire
6002                              Booba
6193                  Ash vs. Evil Dead
Name: title, Length: 62, dtype: str

In [14]:
netflix.sort_values(by='IMDB Rating',ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
727,80187205,Movie,This Is Not What I Expected,Derek Hui,"Takeshi Kaneshiro, Zhou Dongyu, Sun Yizhou, Mi...",China,"October 14, 2017",2017,TV-PG,107 min,"Comedies, International Movies, Romantic Movies",Romance and cuisine mix when a perpetually dis...,10.0
751,80189221,TV Show,The Haunting of Hill House,NaN,"Michiel Huisman, Carla Gugino, Timothy Hutton,...",United States,"October 12, 2018",2018,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries","Flashing between past and present, a fractured...",10.0
3663,80221637,Movie,Maacher Jhol,Pratim D. Gupta,"Ritwick Chakraborty, Mamata Shankar, Paoli Dam...","India, France","January 1, 2018",2017,TV-PG,107 min,"Dramas, International Movies",On his first visit to his home city of Kolkata...,10.0
768,81171871,Movie,GEN HOSHINO STADIUM TOUR “POP VIRUS”,Naoto Amazutsumi,Gen Hoshino,NaN,"October 10, 2019",2019,TV-PG,154 min,"International Movies, Music & Musicals",Singer-songwriter Gen Hoshino takes the stage ...,10.0
649,81193245,TV Show,MONKART,NaN,"Kim Jae-ha, Kwon Ji-hye, Lee Bo-hee, Um Sang-h...",NaN,"October 18, 2019",2017,TV-Y7,1 Season,"Kids' TV, Korean TV Shows",Jin and his dragon monster Draka set out on a ...,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,70260383,Movie,Bleach the Movie: Hell Verse,Noriyuki Abe,"Masakazu Morita, Fumiko Orikasa, Kazuya Nakai,...",Japan,"October 15, 2016",2010,NR,94 min,"Action & Adventure, Anime Features, Sci-Fi & F...",When a group of vicious Sinners plots to escap...,0.0
5096,80998562,Movie,Kaaliyan,Jijo Pancode,"Tini Tom, Meghanathan, Balachandran Chullikadu...",NaN,"August 1, 2018",2017,TV-14,105 min,"Dramas, International Movies","An aggressive, wayward fisherman abandons his ...",0.0
3660,80228146,Movie,Jora 10 Numbaria,Amardeep Singh Gill,"Deep Sidhu, Dharmendra, Ashish Duggal, Aman Hu...",India,"January 1, 2018",2017,TV-MA,135 min,"Action & Adventure, International Movies",The wounds of a traumatic childhood and a corr...,0.0
2903,80184067,TV Show,Amazing Interiors,NaN,NaN,United Kingdom,"July 20, 2018",2018,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...",Meet eccentric homeowners whose seemingly ordi...,0.0
1887,80165850,Movie,Dharam Sankat Mein,Fuwad Khan,"Paresh Rawal, Annu Kapoor, Alka Badola Kaushal...",India,"May 1, 2017",2015,TV-PG,127 min,"Comedies, International Movies",After learning he was adopted from a Muslim co...,0.0

In [20]:
#Get the items with IMDB rating bigger than 8.0 and country with spain
netflix[(netflix['IMDB Rating']>8) & (netflix['country']=='Spain')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
97,80992039,Movie,Two Catalonias,"Álvaro Longoria, Gerardo Olivares",NaN,Spain,"September 28, 2018",2018,TV-MA,117 min,"Documentaries, International Movies",Lawmakers and activists with conflicting ideol...,8.2
334,81003984,Movie,Barça Dreams,Jordi Llompart,"Johan Cruyff, Andrés Iniesta, Gary Lineker, Xa...",Spain,"September 1, 2018",2015,TV-14,122 min,"Documentaries, International Movies, Sports Mo...",Explore the history and philosophies behind on...,9.9
1124,80103512,Movie,The Girl from the Song,Ibai Abad,"Lewis Rainer, Josephine Berry, Charlotte Atkin...",Spain,"November 24, 2017",2016,TV-MA,101 min,"Dramas, Independent Movies, International Movies",When an aspiring musician falls for a carefree...,8.1
1156,80988835,Movie,The Tribe,Fernando Colomo,"Paco León, Carmen Machi, Luis Bermejo, Maribel...",Spain,"November 21, 2018",2018,TV-MA,91 min,"Comedies, International Movies",An executive-turned-viral sensation loses his ...,9.3
1713,81077863,Movie,Born in Gaza,Hernán Zin,NaN,Spain,"May 17, 2019",2014,TV-14,70 min,"Documentaries, International Movies",This documentary focuses on the devastating vi...,9.8
2640,80213115,TV Show,The Alcàsser Murders,Elías León,NaN,Spain,"June 15, 2019",2019,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",New interviews and an up-to-date analysis of e...,8.9
2782,81001804,Movie,100 Days Of Solitude,NaN,NaN,Spain,"July 6, 2018",2018,TV-14,93 min,"Documentaries, International Movies",Spanish photographer José Díaz spends 100 days...,9.0
2785,80168029,Movie,The Skin of the Wolf,Samu Fuentes,"Mario Casas, Irene Escolar, Ruth Díaz",Spain,"July 6, 2018",2018,TV-14,110 min,"Dramas, Independent Movies, International Movies",An animal trapper living in an abandoned mount...,8.6
2876,80232989,Movie,The Warning,Daniel Calparsoro,"Raúl Arévalo, Aura Garrido, Hugo Arbues, Belén...",Spain,"July 24, 2018",2018,TV-MA,93 min,"International Movies, Thrillers","After his friend is shot, Jon finds a mathemat...",9.6
3166,80093104,Movie,Zipi & Zape y la Isla del Capitan,Oskar Santos,"Teo Planell, Toni Gómez, Elena Anaya, Iria Cas...",Spain,"July 1, 2017",2016,TV-PG,105 min,"Children & Family Movies, Comedies","At Christmas, Zip and Zap take a trip with the...",8.2
3378,80997602,Movie,Eye For An Eye,Paco Plaza,"Luis Tosar, Xan Cejudo, Ismael Martínez, Enric...",Spain,"January 15, 2020",2019,TV-MA,108 min,"Dramas, International Movies, Thrillers",A cartel boss is released from prison and unkn...,8.5
3757,80241001,TV Show,Unauthorized Living,NaN,"José Coronado, Álex González, Claudia Traisac,...",Spain,"February 8, 2019",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",When a Galician shipper and drug lord hiding h...,8.5
4521,80988832,Movie,Sad Hill Unearthed,Guillermo de Oliveira,NaN,Spain,"December 15, 2018",2017,TV-14,83 min,"Documentaries, International Movies","An eclectic group of fans of 1966's ""The Good,...",9.6
4797,80114719,Movie,The Laws of Thermodynamics,Mateo Gil,"Vito Sanz, Berta Vázquez, Chino Darín, Vicky L...",Spain,"August 31, 2018",2018,TV-MA,101 min,"Comedies, International Movies, Romantic Movies",A physicist uses the laws of thermodynamics to...,9.3
4812,80215500,TV Show,Cocaine Coast,NaN,"Javier Rey, Tristán Ulloa, Antonio Durán 'Morr...",Spain,"August 3, 2018",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...","In 1980s Galicia, Spain, a young fisherman bec...",9.2
4940,80202810,Movie,Alejandro Sanz: What I Was Is What I Am,"Gervasio Iglesias, Alexis Morante",Alejandro Sanz,Spain,"August 18, 2018",2018,TV-14,102 min,"Documentaries, International Movies, Music & M...",A retrospective look at the life and career of...,9.7
4968,80235578,Movie,The Little Switzerland,Kepa Sojo,"Jon Plazaola, Maggie Civantos, Ingrid García J...",Spain,"August 16, 2019",2019,TV-MA,86 min,"Comedies, International Movies",The discovery of the tomb of William Tell’s so...,9.1
5734,80233258,TV Show,High Seas,NaN,"Ivana Baquero, Jon Kortajarena, Alejandra Onie...",Spain,"November 22, 2019",2019,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, Spanis...",Two sisters discover disturbing family secrets...,8.8
5921,80131505,TV Show,Mutant Busters,NaN,"Dermot Arrigan, James Giblin, Noah Levin, Moll...",Spain,"June 1, 2017",2017,TV-PG,2 Seasons,"Kids' TV, TV Comedies",After a natural disaster known as the Big Fart...,8.4
5991,80064235,TV Show,The Ministry of Time,NaN,"Rodolfo Sancho, Aura Garrido, Nacho Fresneda, ...",Spain,"January 28, 2018",2017,TV-MA,3 Seasons,"International TV Shows, Spanish-Language TV Sh...",Three officers from different eras work for a ...,9.7
6196,80127464,TV Show,Mar de Plástico,NaN,"Rodolfo Sancho, Belén López, Pedro Casablanc, ...",Spain,"April 27, 2017",2017,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, Spanis...",In a town in southern Spain where racial tensi...,9.4

In [22]:
netflix[(netflix['country']=='India') & (netflix['release_year']==2019)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
35,81154455,Movie,Article 15,Anubhav Sinha,"Ayushmann Khurrana, Nassar, Manoj Pahwa, Kumud...",India,"September 6, 2019",2019,TV-MA,125 min,"Dramas, International Movies, Thrillers",The grim realities of caste discrimination com...,7.6
58,81155784,Movie,Watchman,A. L. Vijay,"G.V. Prakash Kumar, Samyuktha Hegde, Suman, Ra...",India,"September 4, 2019",2019,TV-14,93 min,"Comedies, Dramas, International Movies","Rushing to pay off a loan shark, a young man b...",8.3
99,80225885,TV Show,Bard of Blood,NaN,"Emraan Hashmi, Viineet Kumar, Sobhita Dhulipal...",India,"September 27, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,...","Years after a disastrous job in Balochistan, a...",3.9
109,81177238,Movie,Malaal,Mangesh Hadawale,"Meezaan Jaffrey, Sharmin Segal, Chinmaya Surve...",India,"September 26, 2019",2019,TV-14,133 min,"International Movies, Romantic Movies",Class divides become thorns in the budding rom...,1.2
119,81186758,Movie,Oh! Baby (Malayalam),B. V. Nandini Reddy,"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",India,"September 25, 2019",2019,TV-14,146 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...,2.9
120,81186757,Movie,Oh! Baby (Tamil),B. V. Nandini Reddy,"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",India,"September 25, 2019",2019,TV-14,146 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...,5.6
130,81176200,Movie,Manmadhudu 2,Rahul Ravindran,"Nagarjuna Akkineni, Rakul Preet Singh, Lakshmi...",India,"September 23, 2019",2019,TV-MA,152 min,"Comedies, Dramas, International Movies","Under pressure to marry, a perennial bachelor ...",0.7
177,81107545,Movie,Kabir Singh,Sandeep Reddy Vanga,"Shahid Kapoor, Kiara Advani, Suresh Oberoi, Ar...",India,"September 19, 2019",2019,TV-MA,171 min,"Dramas, International Movies, Romantic Movies",An exalted but short-fused surgeon plunges int...,9.2
252,81093951,Movie,Oh! Baby,B. V. Nandini Reddy,"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",India,"September 14, 2019",2019,TV-14,157 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...,9.3
444,81177367,Movie,Noblemen,Vandana Kataria,"Ali Haji, Kunal Kapoor, Muskkaan Jaferi, Hardi...",India,"October 5, 2019",2019,TV-MA,109 min,"Dramas, Independent Movies, International Movies",When he lands the lead in his Christian school...,1.4
475,81177371,Movie,Mehandi Circus,Saravana Rajendran,"Madhampatti Rangaraj, Shweta Tripathi, Vela Ra...",India,"October 30, 2019",2019,TV-14,126 min,"Dramas, International Movies, Romantic Movies","In the early 1990s, the love between a cassett...",4.3
648,81020066,TV Show,Mighty Little Bheem: Diwali,NaN,"Samriddhi Shukla, Nishka Raheja, Arannya Kaur,...",India,"October 18, 2019",2019,TV-Y,1 Season,"Kids' TV, TV Comedies","From decorating his home to devouring sweets, ...",4.9
657,80998890,Movie,Upstarts,Udai Singh Pawar,"Priyanshu Painyuli, Chandrachoor Rai, Shadab K...",India,"October 18, 2019",2019,TV-14,112 min,"Comedies, Dramas, International Movies","Hoping to do good while making millions, three...",8.8
1049,81206389,Movie,Oththa Seruppu Size 7,Parthiban,Parthiban,India,"November 4, 2019",2019,TV-MA,103 min,"Dramas, International Movies, Thrillers","Taken into custody, a murder suspect's theatri...",5.1
1057,81213894,Movie,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,4.7
1097,81194544,Movie,Evvarikee Cheppoddu,Basava Shankar Eeday,"Rakesh Varre, Gargeyi, Vamsi raj Nekkanti, D P...",India,"November 27, 2019",2019,TV-14,134 min,"Comedies, International Movies, Romantic Movies",When caste differences throw a wrench into the...,8.7
1110,81215481,Movie,Pranaam,Sanjiv Jaiswal,"Rajeev Khandelwal, Samiksha Singh, S.M. Zaheer...",India,"November 25, 2019",2019,TV-MA,117 min,"Action & Adventure, Dramas, International Movies",Aspiring to fulfill his father’s dream and bec...,0.9
1170,81217738,Movie,Dorasaani,KVR Mahendra,"Anand Deverakonda, Shivatmika Rajasekhar, Kann...",India,"November 20, 2019",2019,TV-14,134 min,"Dramas, International Movies, Romantic Movies",A village landlord's daughter and an educated ...,8.9
1179,81217739,Movie,Mallesham,Raj R,"Jhansi, Priyadarshi Pullikonda, Ananya Nagalla",India,"November 20, 2019",2019,TV-PG,131 min,"Dramas, Independent Movies, International Movies","A self-trained engineer risks debt, love and r...",8.5
1267,81217737,Movie,Guna 369,Arjun Jandyala,"Adithya Menon, Kartikeya Gummakonda, Anagha LK",India,"November 15, 2019",2019,TV-MA,143 min,"Action & Adventure, Dramas, International Movies",A pampered but kind-hearted average joe ditche...,9.1
1268,81076114,Movie,House Arrest,"Shashanka Ghosh, Samit Basu","Ali Fazal, Shriya Pilgaonkar, Jim Sarbh, Barkh...",India,"November 15, 2019",2019,TV-14,105 min,"Comedies, Independent Movies, International Mo...",A world-weary man’s self-imposed home confinem...,4.3
1361,81189912,Movie,Drive,Tarun Mansukhani,"Jacqueline Fernandez, Sushant Singh Rajput, Bo...",India,"November 1, 2019",2019,TV-14,119 min,"Action & Adventure, International Movies",A notorious thief allies with a street racer f...,0.2
1603,80993095,Movie,Chopsticks,Sachin Yardi,"Abhay Deol, Mithila Palkar, Vijay Raaz",India,"May 31, 2019",2019,TV-MA,101 min,"Comedies, Dramas, Independent Movies",A gifted but insecure woman embarks on a trans...,3.1
1608,80237006,Movie,Mere Pyare Prime Minister,Rakeysh Omprakash Mehra,"Anjali Patil, Om Kanojiya, Niteesh Wadhwa, Mak...",India,"May 31, 2019",2019,TV-MA,103 min,"Dramas, International Movies","When his mother suffers a traumatic incident, ...",5.9
1653,81132060,TV Show,Thackeray,NaN,NaN,India,"May 25, 2019",2019,TV-MA,1 Season,TV Shows,From controversial cartoonist to powerful Mumb...,6.9
1829,81093342,Movie,Sur Sapata,Mangesh Kanthale,"Upendra Limaye, Govind Namdeo, Sanjay Jadhav, ...",India,"May 1, 2019",2019,TV-14,140 min,"Comedies, Dramas, International Movies",A group of small-town students goes for glory ...,2.2
2046,81033429,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ...",6.1
2090,81076756,TV Show,Delhi Crime,NaN,"Shefali Shah, Rajesh Tailang, Rasika Dugal, Ad...",India,"March 22, 2019",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",As Delhi reels in the aftermath of a gang rape...,7.7
2297,80222770,TV Show,Cricket Fever: Mumbai Indians,NaN,NaN,India,"March 1, 2019",2019,TV-MA,1 Season,"Docuseries, International TV Shows",Follow Indian Premier League champions Mumbai ...,6.8
2442,81113918,Movie,Luka Chuppi,Laxman Utekar,"Kartik Aaryan, Kriti Sanon, Pankaj Tripathi, V...",India,"June 7, 2019",2019,TV-14,125 min,"Comedies, International Movies, Romantic Movies","Pretending to marry in order to cohabitate, a ...",3.7
2484,81039384,Movie,Romeo Akbar Walter,Robbie Grewal,"John Abraham, Jackie Shroff, Mouni Roy, Sikand...",India,"June 30, 2019",2019,TV-14,141 min,"Dramas, International Movies, Thrillers","In 1971, a fallen army major’s son is tapped b...",5.4
2501,81128584,Movie,Super Deluxe,Thiagarajan Kumararaja,"Vijay Sethupathi, Fahadh Faasil, Samantha Ruth...",India,"June 29, 2019",2019,TV-MA,176 min,"Comedies, Dramas, International Movies","Sex, stigma and spirituality merge in these ec...",4.7
2533,81108230,Movie,Unbroken,Svati Chakravarty Bhatkal,NaN,India,"June 26, 2019",2019,TV-14,109 min,"Documentaries, International Movies","After the brutal murders of their loved ones, ...",1.6
2583,81131274,Movie,Rakkhosh,"Abhijit Kokate, Srivinay Salian","Sanjay Mishra, Priyanka Bose, Tannishtha Chatt...",India,"June 20, 2019",2019,TV-MA,116 min,"Horror Movies, Independent Movies, Internation...",An asylum patient’s troubled past threatens hi...,2.8
2597,81110386,Movie,Krutant,Datta Mohan Bhandare,"Suyog Rajendra Gorhe, Sandeep Kulkarni, Vidya ...",India,"June 2, 2019",2019,TV-14,114 min,"Dramas, International Movies",When a busy workaholic leaves town to meet fri...,0.6
2635,81123052,Movie,Luckee,Sanjay Jadhav,"Abhay Mahajan, Dipti Sati, Mayur More, Shubhan...",India,"June 15, 2019",2019,TV-14,113 min,"Comedies, International Movies, Romantic Movies",When his friends make a bet that he can woo hi...,9.9
2661,80222951,TV Show,Leila,NaN,"Huma Qureshi, Siddharth, Rahul Khanna, Arif Za...",India,"June 14, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",In a near-future world where an oppressive reg...,6.6
2808,81151899,TV Show,7 (Seven),Nizar Shafi,"Rahman, Havish, Regina Cassandra, Nandita Swet...",India,"July 30, 2019",2019,TV-14,1 Season,TV Shows,Multiple women report their husbands as missin...,6.0
2922,80996338,TV Show,Typewriter,NaN,"Aarna Sharma, Aaryansh Malviya, Mikail Gandhi,...",India,"July 19, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Horror, TV Mysteries",Three young friends in Goa plan to search an o...,2.2
3023,81088331,TV Show,Chhota Bheem,NaN,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"July 11, 2019",2019,TV-Y7,1 Season,Kids' TV,"A brave, energetic little boy with superhuman ...",0.0
3446,81113919,Movie,Made in China,Mikhil Musale,"Rajkummar Rao, Boman Irani, Mouni Roy, Sumeet ...",India,"January 12, 2020",2019,TV-MA,128 min,"Comedies, Dramas, International Movies","After a trip to China, a struggling entreprene...",6.0
3856,81026327,Movie,Firebrand,Aruna Raje,"Usha Jadhav, Girish Kulkarni, Sachin Khedekar,...",India,"February 22, 2019",2019,TV-MA,117 min,"Dramas, International Movies",While she successfully advocates for her femal...,3.6
4095,81157385,Movie,Saaho,Sujeeth,"Prabhas, Shraddha Kapoor, Jackie Shroff, Chunk...",India,"December 8, 2019",2019,TV-MA,172 min,"Action & Adventure, International Movies","In a fictional megalopolis, a stunning underwo...",1.3
4174,81161834,Movie,Albert Pinto Ko Gussa Kyun Aata Hai?,Soumitra Ranade,"Nandita Das, Manav Kaul, Saurabh Shukla, Kisho...",India,"December 31, 2019",2019,TV-MA,85 min,"Dramas, Independent Movies, International Movies","As the police investigate his disappearance, a...",7.0
4620,81217745,Movie,Baby Dolls,Vijay Kumar Arora,"Nirmal Rishi, Sonam Bajwa, Sukhwinder Chahal, ...",India,"December 1, 2019",2019,TV-14,127 min,"Comedies, International Movies, Romantic Movies",When two sisters travel from Canada to Punjab ...,6.2
4623,81217746,Movie,High End Yaariyan,Pankaj Batra,"Ninja, Ranjit Bawa, Jassi Gill, Musskan Sethi,...",India,"December 1, 2019",2019,TV-14,120 min,"Comedies, International Movies, Romantic Movies","From romantic pursuits to their friendship, a ...",4.6
4750,81112446,Movie,Badla,Sujoy Ghosh,"Amitabh Bachchan, Taapsee Pannu, Amrita Singh,...",India,"August 7, 2019",2019,TV-14,117 min,"International Movies, Thrillers","When a woman is accused of killing her lover, ...",4.8
4865,81155859,Movie,Kaake Da Viyah,Rai Yuvraj Bains,"Priti Sapru, Nirmal Rishi, Jordan Sandhu, Prab...",India,"August 23, 2019",2019,TV-PG,133 min,"Comedies, Dramas, International Movies","In this zany comedy, a man is torn between the...",0.7
4869,81155802,Movie,Saavat,Saurabh Sinha,"Smita Tambe, Milind Shirole, Shwetambari Ghute...",India,"August 23, 2019",2019,TV-14,118 min,"Dramas, Independent Movies, International Movies","In rural India, a detective's investigation of...",0.7
4906,81155803,Movie,Uriyadi 2,Vijay Kumar,"Vijay Kumar, Vismaya, Shankar Thas, Abbas, Sud...",India,"August 2, 2019",2019,TV-MA,116 min,"Dramas, International Movies",When a chemical plant's poor conditions cause ...,8.3
4993,81154987,Movie,Chhota Bheem Kungfu Dhamaka,"Rajiv Chilaka, Binayak Das","Sonal Kaushal, Rupa Bhimani, Jigna Bharadhwaj,...",India,"August 15, 2019",2019,TV-Y7-FV,112 min,Children & Family Movies,Chhota Bheem is in China for a martial arts co...,3.5
5019,81147274,Movie,Uyare,Manu Ashokan,"Parvathy, Asif Ali, Tovino Thomas, Siddique, P...",India,"August 14, 2019",2019,TV-14,119 min,"Dramas, International Movies",An aspiring pilot fights for her future – and ...,1.6
5026,81147278,Movie,90 ML,Anita Udeep,"Oviya, Masoom Shankar, Bommu Lakshmi, Monisha ...",India,"August 13, 2019",2019,TV-14,123 min,"Comedies, International Movies, Music & Musicals",Four friends shake up their lives when they me...,7.9
5188,81091424,Movie,Petta (Telugu Version),Karthik Subbaraj,"Rajnikanth, Vijay Sethupathi, M. Sasikumar, Na...",India,"April 7, 2019",2019,TV-14,170 min,"Action & Adventure, Comedies, Dramas","An affable, newly appointed college warden pro...",4.8
5212,81091423,Movie,Petta,Karthik Subbaraj,"Rajnikanth, Vijay Sethupathi, M. Sasikumar, Na...",India,"April 5, 2019",2019,TV-14,170 min,"Action & Adventure, Comedies, Dramas","An affable, newly appointed college warden pro...",4.7
5347,81076749,Movie,Ek Ladki Ko Dekha Toh Aisa Laga,Shelly Chopra Dhar,"Anil Kapoor, Sonam Kapoor, Rajkummar Rao, Juhi...",India,"April 2, 2019",2019,TV-14,120 min,"Comedies, Dramas, International Movies",As her family seeks to marry her off and a hop...,7.2
5359,81033430,Movie,Music Teacher,Sarthak Dasgupta,"Manav Kaul, Amrita Bagchi, Divya Dutta, Neena ...",India,"April 19, 2019",2019,TV-14,102 min,"Dramas, Independent Movies, International Movies",A dejected small-town music teacher grapples w...,2.6
5469,81086434,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,TV-14,118 min,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w...",7.7
5708,81011159,TV Show,Little Things,NaN,"Dhruv Sehgal, Mithila Palkar",India,"November 9, 2019",2019,TV-MA,3 Seasons,"International TV Shows, Romantic TV Shows, TV ...",A cohabiting couple in their 20s navigate the ...,5.0

In [23]:
netflix[netflix.isnull().any(axis=1)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2.2
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.0
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,3.3
5,80163890,TV Show,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,"September 8, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A young journalist is forced into a life of cr...,2.8
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ...",5.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",0.0
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",8.9
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,2.0
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.2
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.6

Replace missing values as -

In [26]:
netflix.fillna(value='-')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB Rating
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,8.9
1,80117401,Movie,Jandino: Whatever it Takes,-,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2.2
2,70234439,TV Show,Transformers Prime,-,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.0
3,80058654,TV Show,Transformers: Robots in Disguise,-,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,3.3
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,9.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,-,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,-,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",0.0
6230,70286564,TV Show,Maron,-,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,-,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",8.9
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,-,-,-,-,2016,-,60 min,Movies,Nursery rhymes and original music for children...,2.0
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,-,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,-,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.2
6233,70153404,TV Show,Friends,-,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,-,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,2.6